* What is this?
This repository contains Docker configuration for running Qdrant with Nginx and SSL.

* What can it do?
It enables the easy implementation of Qdrant API for custom domains.

* Strengths
** Secure API calls with SSL
Even if you include a secret key in the Header, it will be encrypted and secure.

** Automatic SSL renewal
Once you execute docker compose up, the SSL certificate will be automatically renewed internally.

** Set your own Qdrant API key
You can set your own API key, so you can expose your API safely.

** Automatic API setup on custom domains with Nginx
You can implement the Qdrant API for https://your-domain.com/.

* How to use it
** Clone the repository with git.
** Create a .env file
Set QDRANT_DOMAIN to the domain where you want to implement the API.
** Edit qdrant/conf.yaml
Set the api_key to your own sufficiently long secret key.
** Deploy
You need to obtain an SSL certificate in advance and save it to this repository. Therefore, execute create_ssl.sh.

#+begin_src sh
chmod +x create_ssl.sh
sudo ./create_ssl.sh

sudo docker-compose up -d
#+end_src

